import { Blog, BlogStatus } from './blog.model';

export default [
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 1,
    'https://material.angular.io/assets/img/examples/shiba2.jpg'),
    new Blog('First title', 'Naty', new Date(),
     'kjvbdfovbdojfodlvbwpvvhvhdgrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrhvjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvnrfeprf',
      ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 2),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.INACTIVE, 3),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 4),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 5),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.INACTIVE, 6),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.INACTIVE, 7),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 11),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 9),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 10),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.INACTIVE, 31),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 42),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 53),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 64),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 75),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 116),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 97),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 108), 
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.INACTIVE, 39),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 14),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 25),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 36),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 37),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 311),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 49),
    new Blog('First title', 'Naty', new Date(), 'kjvbdfovbdojfodlvbwpnrfeprf', ['holiday', 'project', 'uni'], BlogStatus.ACTIVE, 410),
];
